### ISSUE TITLE
Do you any algorithm in Matlab?

### ISSUE THREAD

**Issue by abranhe** [AllAlgorithms/matlab#1]
<p align="center">
  <img src="https://cdn.abranhe.com/projects/algorithms/algorithms.svg">
</p>

Hi, everyone! 

> Do you know any algorithm implementation in any language, that you wanna share with us?

Open a pull request in any of the programming languages available.

**Comment by SuranjanDaw** [comment]
What algorithm do you need?

**Comment by pranav6670** [comment]
What kind of algorithms do you need in MATLAB? Like basic data structure algorithms?

**Comment by varunkmr19** [comment]
I've added Huffman Encoding Decoding. You can review my pr #8
